### ISSUE TITLE
Terminating app due to uncaught exception 'NSGenericException'

### ISSUE THREAD

**Issue by burhanaksendir** [Christian1313/iOS_Swift_ColorPicker#1]
when I uncheck use size classes:

reason: 'Could not find a navigation controller for segue 'showColorPicker'. Push segues can only be used when the source controller is managed by an instance of UINavigationController.'

How can I solve this problem?

**Comment by Christian1313** [comment]
When you uncheck _Use Size Classes_ Xcode changes the storyboard file. The Segue is changed from _Popover_ to the _(Deprecated) Push_ Segue. This Segue demands that the calling UIViewController is in a UINavigationController.

This is only a problem in the first Example **iOS_Swift_ColorPicker_Storyboard**. 
You can fix this by: 
- Adding a UINavigationController into the storyboard 
- Make the `FirstViewController` the _Root ViewController_ of the added UINavigationController
- Make the UINavigationController the _Initial ViewController_

![screen shot 2015-03-13 at 17 53 32](https://cloud.githubusercontent.com/assets/6986533/6643118/2000b1e2-c9aa-11e4-9ad5-cde67ceb8a5f.png)

Or simply use the second example **iOS_Swift_ColorPicker_Programmatically**, this will work with unchecked _Use Size Classes_. 

In general I recommend using _Size Classes_.

**Comment by burhanaksendir** [comment]
This issue is now resolved. Thank you very much for your detailed explanation.
